---

- name: ensure etcd certs directory
  file:
    path: "{{ etcd_certs_dir }}"
    state: directory
    owner: etcd
    group: etcd
    recurse: yes
    
- name: copy make-ca-cert.sh
  copy:
    src: make-ca-cert.sh
    dest: "{{ etcd_certs_dir }}"
    owner: root
    group: root
    mode: "0500"
  run_once: true
  delegate_to: "{{ groups['etcd-nodes'][0] }}"
  
  
- name: gen certs on the first etcd server
  command:
    "{{ etcd_certs_dir }}/make-ca-cert.sh"
  args:
    creates: "{{ etcd_certs_dir }}/server.crt"
  run_once: true
  delegate_to: "{{ groups['etcd-nodes'][0] }}"
  environment:
    NODE_IPS: "{% for host in groups['etcd-nodes'] %}{{ hostvars[host]['etcd_machine_address'] }}{% if not loop.last %},{% endif %}{% endfor %}"
    NODE_DNS: "{{ groups['etcd-nodes']|join(',') }}"
    CERT_DIR: "{{ etcd_certs_dir }}"
    CERT_GROUP: "{{ etcd_cert_group }}"
    
- name: slurp etcd certs
  slurp:
    src: "{{ item }}"
  register: pki_certs
  run_once: true
  delegate_to: "{{ groups['etcd-nodes'][0] }}"
  with_items:
    - "{{ etcd_ca_file }}"
    - "{{ etcd_cert_file }}"
    - "{{ etcd_key_file }}"
    - "{{ etcd_peer_ca_file }}"
    - "{{ etcd_peer_cert_file }}"
    - "{{ etcd_peer_key_file }}"
    - "{{ etcd_client_cert_file }}"
    - "{{ etcd_client_key_file }}"
    
- name: copy etcd certs to other etcd servers
  copy:
    dest: "{{ item.item }}"
    content: "{{ item.content | b64decode }}"
    owner: etcd
    group: "{{ etcd_cert_group }}"
    mode: 0640
  with_items: "{{ pki_certs.results }}"
  when: inventory_hostname != groups['etcd-nodes'][0]
  
- name: ensure etcd certs perm
  file:
    path: "{{ item }}"
    state: file
    owner: etcd
    mode: 0640
  with_items:
    - "{{ etcd_ca_file }}"
    - "{{ etcd_cert_file }}"
    - "{{ etcd_key_file }}"
    - "{{ etcd_peer_ca_file }}"
    - "{{ etcd_peer_cert_file }}"
    - "{{ etcd_peer_key_file }}"
    - "{{ etcd_client_cert_file }}"
    - "{{ etcd_client_key_file }}"
